### PR TITLE
Frontend profile fix

### LINKED ISSUE #145: Fix profile page according to the changes in backend
Profile API is changed with #135. Frontend should be updated accordingly.
### I'm submitting a ...

- [x] bug report
- [ ] feature request
- [ ] support request

### LINKED ISSUE #149: Add comments to profiles
Users will be able to comment to each others profile.

### I'm submitting a ...

- [ ] bug report
- [x] feature request
- [ ] support request

### Additional Notes
Depends on #145 
Comment API #141

### PR DESCRIPTION
**Pull request by kilicbaran**
# Description

* Fixed profile page and profile edit page according to new backend profile API
* Added profile page for other users
* Added comments to profile pages
* Added milestone information to bids in project page

Note: This pull request requires the command "npm install" to be run once.

Fixes #145 
Fixes #149

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by afcelimli** [comment]
I could edit a users different profiles with different photos and description text which is nice. However when I tried to create a project with file and location it couldn't send request to server. Also when I send bid to a project, it didn't make a request to server.

**Comment by kilicbaran** [comment]
The backend part in this branch is an older version. Can you try it again with the current backend in the develop branch?

**Comment by afcelimli** [comment]
@meverg can you review this branch?

**Comment by kilicbaran** [comment]
I merge this pull request to make the last checks for the whole frontend before our second customer milestone.

**Pull request merged**
