### PR TITLE
Frontend project offer

### LINKED ISSUE #127: Add bids,comments and map to project page
### I'm submitting a ...

- [ ] bug report
- [x] feature request
- [ ] support request

### PR DESCRIPTION
**Pull request by kilicbaran**
# Description

* Add bidders section to project page (not connected to backend)
* Add bidding form to project page (not connected to backend)
* Add comment section to project page (not connected to backend)
* Add location map to project page (connected to backend)
* Add location map and search box to project creation page (connected to backend)
* Add (uncommented the code) role toggle (not connected to backend)

Fixes #127 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by afcelimli** [comment]
I'm gonna review this as soon as possible.

**Review by afcelimli — COMMENTED** [review]
Couldn't login or register. When I look backend logs, there are no requests. Do you have any idea about possible reasons?

**Comment by kilicbaran** [comment]
I added an additional step to run the server. You can find it in [readme](https://github.com/bounswe/bounswe2018group10/blob/develop/application/frontend/README.md). You have to set some environment variables.

**Comment by kilicbaran** [comment]
Since the pull request https://github.com/bounswe/bounswe2018group10/pull/136 is a branch of this branch (it already contains the commits in this branch) and is approved, I merge this branch.

**Pull request merged**
