### PR TITLE
Frontend filters

### LINKED ISSUE #166: Search Filtering
* User will be able to filter and sort projects according to budget and deadline dates.
* User will be able to sort bids by date and bid amount.

Backend API: https://github.com/bounswe/bounswe2018group10/pull/163

### I'm submitting a ...

- [ ] bug report
- [x] feature request
- [ ] support request

### PR DESCRIPTION
**Pull request by kilicbaran**
# Description
* User is able to filter and sort projects according to budget and deadline date.
* User is able to filter projects according to tags.
* User is able to sort bids by date and bid amount.

Fixes #166

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by alimturkmen — COMMENTED** [review]
I tried the filter, it is great. However, I couldn't see my project as a client. There is a bug about that. Therefore, I couldn't check whether sorting the bids works or not.

**Comment by kilicbaran** [comment]
I cannot reproduce the bug :(

**Comment by alimturkmen** [comment]
I still can't see the projects I created. I am approving the pull request but, I think, someone else also should try it.

**Review by alimturkmen — APPROVED** [review]

**Comment by alimturkmen** [comment]
I can't produce the same bug now. Probably, I misdid something that time, sorry about that. Great job, thanks :)

**Pull request merged**
